---
- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: Verify Apache is serving web request
      uri:
        url: http://localhost/
        status_code: 200
        return_content: true
      register: this
      failed_when: "'Hello' not in this.content"
